
# Bokeh for Time Series Analysis
<hr style="border: 2px solid black;">


<img src="./images/bokeh.png" alt="bokeh Logo" width="1000"/>
<hr style="border: 2px solid black;">

<img src="./images/bokeh_at_ag_glance.png" alt="bokeh Logo" width="1000"/>
<hr style="border: 2px solid black;">
**Introduction to Bokeh**
Bokeh is an interactive visualization library for Python that targets modern web browsers for presentation.
Unlike Matplotlib, which is primarily designed for static plots, Bokeh excels at creating
interactive plots and dashboards. It can handle large datasets and streaming data,
making it suitable for real-time applications.

**Key Features of Bokeh:**

* **Interactivity:** Built-in support for zooming, panning, hovering, and other interactive tools.
* **Web-Focused:** Generates HTML and JavaScript, making it easy to embed plots in web pages.
* **High Performance:** Can handle large datasets efficiently.
* **Versatility:** Supports a wide range of plot types (lines, bars, scatter plots, etc.).

<hr style="border: 2px solid black;">


**Documentation:**

For comprehensive documentation, please refer to the official Bokeh website: [https://docs.bokeh.org/en/latest/](https://docs.bokeh.org/en/latest/)


<hr style="border: 2px solid black;">


**Lab Exercise:**

Your task is to recreate the time series analysis lab we previously conducted using Pandas,
Matplotlib, and Seaborn, but this time, utilize the Bokeh library for visualization.
This will involve:

1.  Loading and preprocessing the "AirPassengersDates.csv" dataset.
2.  Creating interactive Bokeh plots for:
    * Time series line plots
    * Bar plots of aggregated data
    * Visualizing mean and standard deviation
    * Outlier detection
    * Resampling (upsampling and downsampling)
    * Lag analysis
    * Autocorrelation

Pay close attention to Bokeh's features for interactivity (tools, hover effects) and
its handling of data sources. Aim to replicate the insights and visualizations
from the previous lab while leveraging Bokeh's strengths.

Good luck!
<hr style="border: 2px solid black;">

## 1. Imports & Setup

In [1]:
# Install dependencies (Google Colab)
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "bokeh", "statsmodels"])

import pandas as pd
import numpy as np

from bokeh.plotting import figure, show, output_notebook
from bokeh.models import (
    ColumnDataSource, HoverTool, Span, Band,
    NumeralTickFormatter, DatetimeTickFormatter,
    BoxAnnotation, Label, Range1d
)
from bokeh.layouts import column, row, gridplot
from bokeh.palettes import Category10, Spectral6, Blues8
from bokeh.transform import factor_cmap

# Render plots inline in the notebook
output_notebook()

print("Imports successful ✓")

Imports successful ✓

## 2. Loading & Preprocessing the Dataset

In [2]:
# ── Create AirPassengersDates.csv directly (no upload needed) ──────────────
import io

raw_data = """Date,Passengers
1949-01-01,112
1949-02-01,118
1949-03-01,132
1949-04-01,129
1949-05-01,121
1949-06-01,135
1949-07-01,148
1949-08-01,148
1949-09-01,136
1949-10-01,119
1949-11-01,104
1949-12-01,118
1950-01-01,115
1950-02-01,126
1950-03-01,141
1950-04-01,135
1950-05-01,125
1950-06-01,149
1950-07-01,170
1950-08-01,170
1950-09-01,158
1950-10-01,133
1950-11-01,114
1950-12-01,140
1951-01-01,145
1951-02-01,150
1951-03-01,178
1951-04-01,163
1951-05-01,172
1951-06-01,178
1951-07-01,199
1951-08-01,199
1951-09-01,184
1951-10-01,162
1951-11-01,146
1951-12-01,166
1952-01-01,171
1952-02-01,180
1952-03-01,193
1952-04-01,181
1952-05-01,183
1952-06-01,218
1952-07-01,230
1952-08-01,242
1952-09-01,209
1952-10-01,191
1952-11-01,172
1952-12-01,194
1953-01-01,196
1953-02-01,196
1953-03-01,236
1953-04-01,235
1953-05-01,229
1953-06-01,243
1953-07-01,264
1953-08-01,272
1953-09-01,237
1953-10-01,211
1953-11-01,180
1953-12-01,201
1954-01-01,204
1954-02-01,188
1954-03-01,235
1954-04-01,227
1954-05-01,234
1954-06-01,264
1954-07-01,302
1954-08-01,293
1954-09-01,259
1954-10-01,229
1954-11-01,203
1954-12-01,229
1955-01-01,242
1955-02-01,233
1955-03-01,267
1955-04-01,269
1955-05-01,270
1955-06-01,315
1955-07-01,364
1955-08-01,347
1955-09-01,312
1955-10-01,274
1955-11-01,237
1955-12-01,278
1956-01-01,284
1956-02-01,277
1956-03-01,317
1956-04-01,313
1956-05-01,318
1956-06-01,374
1956-07-01,413
1956-08-01,405
1956-09-01,355
1956-10-01,306
1956-11-01,271
1956-12-01,306
1957-01-01,315
1957-02-01,301
1957-03-01,356
1957-04-01,348
1957-05-01,355
1957-06-01,422
1957-07-01,465
1957-08-01,467
1957-09-01,404
1957-10-01,347
1957-11-01,305
1957-12-01,336
1958-01-01,340
1958-02-01,318
1958-03-01,362
1958-04-01,348
1958-05-01,363
1958-06-01,435
1958-07-01,491
1958-08-01,505
1958-09-01,404
1958-10-01,359
1958-11-01,310
1958-12-01,337
1959-01-01,360
1959-02-01,342
1959-03-01,406
1959-04-01,396
1959-05-01,420
1959-06-01,472
1959-07-01,548
1959-08-01,559
1959-09-01,463
1959-10-01,407
1959-11-01,362
1959-12-01,405
1960-01-01,417
1960-02-01,391
1960-03-01,419
1960-04-01,461
1960-05-01,472
1960-06-01,535
1960-07-01,622
1960-08-01,606
1960-09-01,508
1960-10-01,461
1960-11-01,390
1960-12-01,432
"""

# Write to a CSV file in the Colab environment
with open("AirPassengersDates.csv", "w") as f:
    f.write(raw_data)

print("✓ AirPassengersDates.csv created successfully!")

✓ AirPassengersDates.csv created successfully!

In [3]:
# Load the AirPassengers dataset
df = pd.read_csv("AirPassengersDates.csv", parse_dates=["Date"], index_col="Date")
df.columns = ["Passengers"]

print("Shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

print("\nBasic statistics:")
display(df.describe())

print("\nMissing values:", df.isnull().sum().values[0])
print("Date range:", df.index.min(), "→", df.index.max())

Shape: (144, 1)

First 5 rows:

            Passengers
Date
1949-01-01         112
1949-02-01         118
1949-03-01         132
1949-04-01         129
1949-05-01         121

Basic statistics:

       Passengers
count  144.000000
mean   280.298611
std    119.966317
min    104.000000
25%    180.000000
50%    265.500000
75%    360.500000
max    622.000000

Missing values: 0
Date range: 1949-01-01 00:00:00 → 1960-12-01 00:00:00

## 3. Time Series Line Plot

Basic interactive line plot of monthly passenger counts over time.

In [4]:
source = ColumnDataSource(data={
    "date":       df.index,
    "passengers": df["Passengers"],
})

p = figure(
    title="Air Passengers – Monthly Count (1949-1960)",
    x_axis_type="datetime",
    width=900, height=400,
    tools="pan,wheel_zoom,box_zoom,reset,save",
    toolbar_location="above",
)

p.line("date", "passengers", source=source,
       line_width=2, color="steelblue", legend_label="Passengers")
p.circle("date", "passengers", source=source,
         size=5, color="steelblue", alpha=0.5)

p.add_tools(HoverTool(
    tooltips=[
        ("Date",       "@date{%b %Y}"),
        ("Passengers", "@passengers{0,0}"),
    ],
    formatters={"@date": "datetime"},
    mode="vline"
))

p.xaxis.axis_label = "Date"
p.yaxis.axis_label = "Number of Passengers"
p.xaxis.formatter = DatetimeTickFormatter(months="%b %Y", years="%Y")
p.legend.location = "top_left"
p.grid.grid_line_alpha = 0.3

show(p)

## 4. Bar Plot – Average Passengers by Month

Aggregated bar chart showing the average number of passengers per calendar month.

In [5]:
month_names = ["Jan","Feb","Mar","Apr","May","Jun",
               "Jul","Aug","Sep","Oct","Nov","Dec"]

monthly_avg = df.groupby(df.index.month)["Passengers"].mean()
monthly_std = df.groupby(df.index.month)["Passengers"].std()

src_bar = ColumnDataSource(data={
    "months":  month_names,
    "avg":     monthly_avg.values,
    "std":     monthly_std.values,
    "upper":   (monthly_avg + monthly_std).values,
    "lower":   (monthly_avg - monthly_std).values,
})

p2 = figure(
    title="Average Passengers by Month",
    x_range=month_names,
    width=800, height=400,
    tools="pan,wheel_zoom,box_zoom,reset,save",
    toolbar_location="above",
)

p2.vbar(x="months", top="avg", source=src_bar,
        width=0.7,
        color=factor_cmap("months", palette=Spectral6 + Spectral6, factors=month_names),
        line_color="white", alpha=0.85, legend_label="Mean")

# Error bars (std)
p2.segment(x0="months", y0="lower", x1="months", y1="upper",
           source=src_bar, line_width=2, color="black")
p2.rect(x="months", y="upper", width=0.2, height=0.5,
        source=src_bar, color="black")
p2.rect(x="months", y="lower", width=0.2, height=0.5,
        source=src_bar, color="black")

p2.add_tools(HoverTool(tooltips=[
    ("Month",  "@months"),
    ("Mean",   "@avg{0.0}"),
    ("± Std",  "@std{0.0}"),
]))

p2.xaxis.axis_label = "Month"
p2.yaxis.axis_label = "Average Passengers"
p2.legend.location = "top_left"
p2.grid.grid_line_alpha = 0.3

show(p2)

## 5. Mean & Standard Deviation Band

Rolling mean ± 1 standard deviation displayed as a shaded band.

In [6]:
window = 12   # 12-month rolling window

roll_mean = df["Passengers"].rolling(window=window).mean()
roll_std  = df["Passengers"].rolling(window=window).std()

src_band = ColumnDataSource(data={
    "date":    df.index,
    "raw":     df["Passengers"],
    "mean":    roll_mean,
    "upper":   roll_mean + roll_std,
    "lower":   roll_mean - roll_std,
})

p3 = figure(
    title=f"Rolling Mean ± 1 Std (window={window} months)",
    x_axis_type="datetime",
    width=900, height=420,
    tools="pan,wheel_zoom,box_zoom,reset,save",
)

# Shaded band
band = Band(base="date", lower="lower", upper="upper",
            source=src_band, fill_color="steelblue", fill_alpha=0.25,
            line_color="steelblue", line_alpha=0.4)
p3.add_layout(band)

# Raw series
p3.line("date", "raw", source=src_band,
        line_width=1.5, color="lightsteelblue", alpha=0.7, legend_label="Raw")
# Rolling mean
p3.line("date", "mean", source=src_band,
        line_width=2.5, color="darkblue", legend_label="Rolling Mean")

p3.add_tools(HoverTool(
    tooltips=[
        ("Date",         "@date{%b %Y}"),
        ("Raw",          "@raw{0,0}"),
        ("Rolling Mean", "@mean{0.0}"),
        ("Upper Band",   "@upper{0.0}"),
        ("Lower Band",   "@lower{0.0}"),
    ],
    formatters={"@date": "datetime"},
    mode="vline"
))

p3.xaxis.axis_label  = "Date"
p3.yaxis.axis_label  = "Passengers"
p3.xaxis.formatter   = DatetimeTickFormatter(months="%b %Y", years="%Y")
p3.legend.location   = "top_left"
p3.grid.grid_line_alpha = 0.3

show(p3)

## 6. Outlier Detection

Points that fall outside **mean ± 2 standard deviations** (global) are flagged as outliers and highlighted in red.

In [7]:
global_mean = df["Passengers"].mean()
global_std  = df["Passengers"].std()
threshold   = 2

upper_bound = global_mean + threshold * global_std
lower_bound = global_mean - threshold * global_std

is_outlier  = (df["Passengers"] > upper_bound) | (df["Passengers"] < lower_bound)
normal_df   = df[~is_outlier]
outlier_df  = df[is_outlier]

src_normal  = ColumnDataSource(data={"date": normal_df.index, "pass": normal_df["Passengers"]})
src_outlier = ColumnDataSource(data={"date": outlier_df.index, "pass": outlier_df["Passengers"]})

p4 = figure(
    title="Outlier Detection (Mean ± 2 Std)",
    x_axis_type="datetime",
    width=900, height=420,
    tools="pan,wheel_zoom,box_zoom,reset,save",
)

# Shaded outlier zones
p4.add_layout(BoxAnnotation(bottom=upper_bound, fill_alpha=0.08, fill_color="red"))
p4.add_layout(BoxAnnotation(top=lower_bound,    fill_alpha=0.08, fill_color="red"))

# Threshold lines
p4.add_layout(Span(location=upper_bound, dimension="width",
                   line_color="red", line_dash="dashed", line_width=1.5))
p4.add_layout(Span(location=lower_bound, dimension="width",
                   line_color="red", line_dash="dashed", line_width=1.5))
p4.add_layout(Span(location=global_mean,  dimension="width",
                   line_color="green", line_dash="dotted", line_width=1.5))

# Normal points
p4.line("date", "pass", source=src_normal,
        line_width=2, color="steelblue", legend_label="Normal")
p4.circle("date", "pass", source=src_normal,
          size=5, color="steelblue", alpha=0.6)

# Outlier points
p4.circle("date", "pass", source=src_outlier,
          size=10, color="red", alpha=0.9, legend_label="Outlier")

p4.add_tools(HoverTool(
    tooltips=[("Date", "@date{%b %Y}"), ("Passengers", "@pass{0,0}")],
    formatters={"@date": "datetime"}
))

p4.xaxis.axis_label = "Date"
p4.yaxis.axis_label = "Passengers"
p4.xaxis.formatter  = DatetimeTickFormatter(months="%b %Y", years="%Y")
p4.legend.location  = "top_left"
p4.grid.grid_line_alpha = 0.3

print(f"Global mean:   {global_mean:.1f}")
print(f"Upper bound:   {upper_bound:.1f}")
print(f"Lower bound:   {lower_bound:.1f}")
print(f"Outliers found: {is_outlier.sum()}")
if not outlier_df.empty:
    display(outlier_df)

show(p4)

Global mean:   280.3
Upper bound:   520.2
Lower bound:   40.4
Outliers found: 5

            Passengers
Date
1959-07-01         548
1959-08-01         559
1960-06-01         535
1960-07-01         622
1960-08-01         606

## 7. Resampling

### 7a. Downsampling – Annual Mean

Resample the monthly data to a yearly frequency (mean).

In [ ]:
# --- Downsampling: yearly mean ---
df_yearly = df.resample("YE").mean()

src_yearly = ColumnDataSource(data={
    "date": df_yearly.index,
    "pass": df_yearly["Passengers"],
})

p5 = figure(
    title="Downsampling – Yearly Mean Passengers",
    x_axis_type="datetime",
    width=700, height=380,
    tools="pan,wheel_zoom,box_zoom,reset,save",
)

p5.vbar(x="date", top="pass", source=src_yearly,
        width=2.5e7, color="coral", alpha=0.8, legend_label="Yearly Mean")
p5.line("date", "pass", source=src_yearly,
        line_width=2, color="darkred", legend_label="Trend")

p5.add_tools(HoverTool(
    tooltips=[("Year", "@date{%Y}"), ("Mean Passengers", "@pass{0.0}")],
    formatters={"@date": "datetime"}
))

p5.xaxis.axis_label = "Year"
p5.yaxis.axis_label = "Mean Passengers"
p5.xaxis.formatter  = DatetimeTickFormatter(years="%Y")
p5.legend.location  = "top_left"
p5.grid.grid_line_alpha = 0.3

show(p5)

### 7b. Upsampling – Weekly with Linear Interpolation

Upsample from monthly to **weekly** frequency using linear interpolation.

In [ ]:
# --- Upsampling: weekly with linear interpolation ---
df_weekly = df.resample("W").interpolate(method="linear")

src_monthly = ColumnDataSource(data={"date": df.index,        "pass": df["Passengers"]})
src_weekly  = ColumnDataSource(data={"date": df_weekly.index, "pass": df_weekly["Passengers"]})

p6 = figure(
    title="Upsampling – Weekly (Linear Interpolation) vs Monthly",
    x_axis_type="datetime",
    width=900, height=420,
    tools="pan,wheel_zoom,box_zoom,reset,save",
)

p6.line("date", "pass", source=src_weekly,
        line_width=1.5, color="orange", alpha=0.7, legend_label="Weekly (interpolated)")
p6.circle("date", "pass", source=src_monthly,
          size=8, color="navy", alpha=0.9, legend_label="Monthly (original)")

p6.add_tools(HoverTool(
    tooltips=[("Date", "@date{%d %b %Y}"), ("Passengers", "@pass{0.0}")],
    formatters={"@date": "datetime"}
))

p6.xaxis.axis_label = "Date"
p6.yaxis.axis_label = "Passengers"
p6.xaxis.formatter  = DatetimeTickFormatter(months="%b %Y", years="%Y")
p6.legend.location  = "top_left"
p6.grid.grid_line_alpha = 0.3

print(f"Monthly points: {len(df)}   →   Weekly points: {len(df_weekly)}")
show(p6)

Monthly points: 144   →   Weekly points: 623

BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.

## 8. Lag Analysis

Scatter plot of the series against itself shifted by **k** lags (months).  
A strong linear pattern indicates high autocorrelation at that lag.

In [ ]:
lags_to_plot = [1, 6, 12, 24]

lag_figures = []
for lag in lags_to_plot:
    lagged   = df["Passengers"].shift(lag).dropna()
    original = df["Passengers"].loc[lagged.index]

    src_lag = ColumnDataSource(data={
        "x":    original.values,
        "y":    lagged.values,
        "date": original.index,
    })

    # Correlation coefficient for title
    corr = np.corrcoef(original.values, lagged.values)[0, 1]

    plag = figure(
        title=f"Lag {lag} month(s)  –  r = {corr:.3f}",
        width=350, height=350,
        tools="pan,wheel_zoom,reset",
    )
    plag.circle("x", "y", source=src_lag,
                size=6, color="steelblue", alpha=0.6)

    # Reference line y = x
    mn, mx = original.min(), original.max()
    plag.line([mn, mx], [mn, mx], line_dash="dashed", color="red", line_width=1.5)

    plag.add_tools(HoverTool(
        tooltips=[
            ("Date",         "@date{%b %Y}"),
            ("t",            "@x{0,0}"),
            (f"t-{lag}",     "@y{0,0}"),
        ],
        formatters={"@date": "datetime"}
    ))

    plag.xaxis.axis_label = "Passengers at t"
    plag.yaxis.axis_label = f"Passengers at t-{lag}"
    plag.grid.grid_line_alpha = 0.3
    lag_figures.append(plag)

grid = gridplot([lag_figures[:2], lag_figures[2:]])
show(grid)

BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.

## 9. Autocorrelation (ACF)

The **Autocorrelation Function (ACF)** measures the correlation between the series and its own lagged values.  
Significant spikes every **12 lags** reveal the yearly seasonality of the data.

In [ ]:
from statsmodels.tsa.stattools import acf

n_lags = 40
acf_values, conf_int = acf(df["Passengers"], nlags=n_lags, alpha=0.05)

lags   = np.arange(n_lags + 1)
ci_up  = conf_int[:, 1] - acf_values
ci_low = acf_values - conf_int[:, 0]

# Significance threshold ≈ 1.96 / sqrt(n)
sig_threshold = 1.96 / np.sqrt(len(df))

colors = ["crimson" if abs(v) > sig_threshold else "steelblue" for v in acf_values]

src_acf = ColumnDataSource(data={
    "lag":    lags,
    "acf":    acf_values,
    "color":  colors,
    "ci_up":  ci_up,
    "ci_low": ci_low,
})

p7 = figure(
    title="Autocorrelation Function (ACF)",
    width=900, height=420,
    x_range=Range1d(-0.5, n_lags + 0.5),
    tools="pan,wheel_zoom,box_zoom,reset,save",
)

# Confidence interval band
p7.add_layout(BoxAnnotation(
    bottom=-sig_threshold, top=sig_threshold,
    fill_color="lightblue", fill_alpha=0.2,
    line_color="steelblue", line_dash="dashed"
))

# Vertical stems
p7.segment(x0="lag", y0=0, x1="lag", y1="acf",
           source=src_acf, line_width=2, line_color="color")
p7.circle("lag", "acf", source=src_acf,
          size=8, color="color", alpha=0.9)

# Zero baseline
p7.add_layout(Span(location=0, dimension="width",
                   line_color="black", line_width=1))

p7.add_tools(HoverTool(tooltips=[
    ("Lag",  "@lag"),
    ("ACF",  "@acf{0.000}"),
]))

p7.xaxis.axis_label = "Lag (months)"
p7.yaxis.axis_label = "Autocorrelation"
p7.grid.grid_line_alpha = 0.3

print(f"Significance threshold: ±{sig_threshold:.4f}")
show(p7)

Significance threshold: ±0.1633

BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.

## 10. Yearly Trend Comparison

Each year's monthly profile plotted on the same axis to visualise the growth in passenger numbers over the decade.

In [ ]:
years  = sorted(df.index.year.unique())
palette = Blues8[::-1]  # light → dark

p8 = figure(
    title="Monthly Profile per Year",
    x_range=month_names,
    width=900, height=420,
    tools="pan,wheel_zoom,box_zoom,reset,save",
)

for i, year in enumerate(years):
    year_df = df[df.index.year == year].copy()
    year_df["month_name"] = year_df.index.month.map(
        lambda m: month_names[m - 1]
    )
    year_df = year_df.set_index("month_name").reindex(month_names)

    src_y = ColumnDataSource(data={
        "month":  month_names,
        "pass":   year_df["Passengers"].values,
    })

    color = palette[i % len(palette)]
    p8.line("month", "pass", source=src_y,
            line_width=2, color=color, alpha=0.85, legend_label=str(year))
    p8.circle("month", "pass", source=src_y,
              size=5, color=color, alpha=0.7)

p8.add_tools(HoverTool(tooltips=[
    ("Month",      "@month"),
    ("Passengers", "@pass{0,0}"),
]))

p8.xaxis.axis_label = "Month"
p8.yaxis.axis_label = "Passengers"
p8.legend.location  = "top_left"
p8.legend.label_text_font_size = "9pt"
p8.grid.grid_line_alpha = 0.3

show(p8)

BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.
BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.

## 11. Summary Dashboard

Side-by-side overview: raw series + rolling mean (top) and yearly bar chart (bottom).

In [ ]:
# ---- Top panel: raw + rolling mean ----
src_dash = ColumnDataSource(data={
    "date": df.index,
    "raw":  df["Passengers"],
    "mean": df["Passengers"].rolling(12).mean(),
})

pd_top = figure(
    title="Raw Series & 12-Month Rolling Mean",
    x_axis_type="datetime",
    width=900, height=300,
    tools="pan,wheel_zoom,box_zoom,reset,save",
)
pd_top.line("date", "raw",  source=src_dash,
            line_width=1.5, color="lightsteelblue", legend_label="Raw")
pd_top.line("date", "mean", source=src_dash,
            line_width=2.5, color="darkblue", legend_label="12-M Mean")
pd_top.add_tools(HoverTool(
    tooltips=[("Date", "@date{%b %Y}"), ("Raw", "@raw{0,0}"), ("Mean", "@mean{0.0}")],
    formatters={"@date": "datetime"}, mode="vline"
))
pd_top.xaxis.formatter = DatetimeTickFormatter(months="%b %Y", years="%Y")
pd_top.legend.location = "top_left"
pd_top.grid.grid_line_alpha = 0.3

# ---- Bottom panel: yearly bar ----
yearly_sum = df.resample("YE").sum()
year_labels = [str(y) for y in yearly_sum.index.year]

src_ysum = ColumnDataSource(data={
    "year": year_labels,
    "pass": yearly_sum["Passengers"].values,
})

pd_bot = figure(
    title="Total Passengers per Year",
    x_range=year_labels,
    width=900, height=280,
    tools="pan,wheel_zoom,box_zoom,reset,save",
)
pd_bot.vbar(x="year", top="pass", source=src_ysum,
            width=0.7, color="steelblue", alpha=0.8)
pd_bot.add_tools(HoverTool(tooltips=[
    ("Year", "@year"), ("Total", "@pass{0,0}"),
]))
pd_bot.xaxis.axis_label = "Year"
pd_bot.yaxis.axis_label = "Total Passengers"
pd_bot.grid.grid_line_alpha = 0.3

dashboard = column(pd_top, pd_bot)
show(dashboard)